workflow:
  auto_cancel:
    on_new_commit: conservative
  rules:
    # Create a pipeline for MR commits
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Create a pipeline for commits to main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Don't create a pipeline for regular commits if we're already 
    # creating an MR pipeline
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # Create a pipeline for regular commits otherwise
    - if: $CI_COMMIT_BRANCH

variables:
  LUTE_CI_REGISTRY: registry.gitlab.com/lute-dev/ci-container
  CI_IMAGE_NAME: lute-ci
  CI_IMAGE_TAG: 0.1.0
  CI_IMAGE: $LUTE_CI_REGISTRY/$CI_IMAGE_NAME:$CI_IMAGE_TAG
  LUTE_CI_AUTH: $(echo -n "$CI_REGISTRY_USERNAME:$CI_JOB_TOKEN) | base64

stages:
  - lint
  - test


lint:python:
  stage: lint
  image: $CI_IMAGE
  script:
    - pip install -r requirements.txt
    - black src/

test:unit:
  stage: test
  image: $CI_IMAGE
  script:
    - pip install -r requirements.txt
    - pytest -v -m unit
